Add ByteRangeHelper
aspnet/HttpAbstractions pull request #807
Opened 2017-03-31 21:31 UTC by jbagga

Moved [RangeHelper](https://github.com/aspnet/StaticFiles/blob/dev/src/Microsoft.AspNetCore.StaticFiles/Infrastructure/RangeHelpers.cs) from StaticFiles and added tests

cc @Tratcher @pranavkm

2017-03-31 21:31 UTC, dnfclas commented
@jbagga,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-31 23:34 UTC, pranavkm requested changes

2017-03-31 23:34 UTC, pranavkm commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +    internal static class ByteRangeHelper
Aren't you using this type outside this repo?

2017-03-31 23:34 UTC, pranavkm commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +            IList<RangeItemHeaderValue> normalizedRanges = new List<RangeItemHeaderValue>(ranges.Count);
`var` all day everyday

2017-04-03 18:22 UTC, jbagga commented
@pranavkm @Tratcher Updated

2017-04-03 19:19 UTC, pranavkm approved these changes
Once @Tratcher is happy

2017-04-03 19:19 UTC, pranavkm commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +            var normalizedRanges = new List<RangeItemHeaderValue>(ranges.Count);
```C#
if (ranges.Count == 0)
{
  return Array.Empty<RangeItemHeaderValue>();
}

var normalizedRanges = new List<RangeItemHeaderValue>(ranges.Count);
...
```

2017-04-03 20:52 UTC, Tratcher commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +        public static IList<RangeItemHeaderValue> NormalizeRanges(ICollection<RangeItemHeaderValue> ranges, long length)
Split out a second method `public static RangeItemHeaderValue NormalizeRange(RangeItemHeaderValue range, long length)`. Most of your tests only apply to this subset of the functionality.

2017-04-03 22:34 UTC, jbagga commented
@pranavkm @Tratcher Updated

2017-04-03 22:39 UTC, pranavkm commented on test/Microsoft.AspNetCore.WebUtilities.Tests/ByteRangeHelperTest.cs
> +using System.Collections.Generic;
`System.*` goes first

2017-04-03 23:23 UTC, Tratcher requested changes

2017-04-03 23:23 UTC, Tratcher commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +            if (length == 0)
Why doesn't this return `Array.Empty<RangeItemHeaderValue>();` too?

2017-04-03 23:23 UTC, Tratcher commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +                    // Not satisfiable, skip/discard.
Hmm, my idea to make this a sub method just regressed this bit. You removed the continue that would have skipped adding the result. The behavior is now quite different. Is there a test case for this condition?
https://github.com/aspnet/StaticFiles/blob/f73dc5cebea6c08485662f1703d2aba1fc0cd408/src/Microsoft.AspNetCore.StaticFiles/Infrastructure/RangeHelpers.cs#L34

2017-04-03 23:54 UTC, jbagga commented
@Tratcher Added test cases to skip invalid ranges. Thank you for pointing it out!

2017-04-04 04:45 UTC, Tratcher approved these changes

2017-04-06 18:52 UTC, jbagga commented
@Tratcher @pranavkm Added another method and tests

2017-04-06 19:06 UTC, Tratcher requested changes

2017-04-06 19:06 UTC, Tratcher commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +        public static bool ParseRange(HttpContext context, DateTimeOffset lastModified, EntityTagHeaderValue etag)
This is less efficient the the original in StaticFiles. GetTypedHeaders creates a new structure (which you call multiple times) and .Range parses the header again without any caching. If you want to call it ParseRange then at least return the Range object.

2017-04-06 19:06 UTC, Tratcher commented on src/Microsoft.AspNetCore.WebUtilities/ByteRangeHelper.cs
> +        public static bool ParseRange(HttpContext context, DateTimeOffset lastModified, EntityTagHeaderValue etag)
Doc comments

2017-04-06 19:06 UTC, Tratcher commented on src/Microsoft.AspNetCore.WebUtilities/Microsoft.AspNetCore.WebUtilities.csproj
> +    <ProjectReference Include="..\Microsoft.AspNetCore.Http.Extensions\Microsoft.AspNetCore.Http.Extensions.csproj" />
This layering is problematic. WebUtilities should not add these dependencies which makes it impossible to write your method here... I think you'll have to move it to Http.Extensions reduce the inputs.

2017-04-06 21:44 UTC, jbagga commented
@Tratcher @pranavkm Added doc comments and moved `ParseRange` to `Extensions`

2017-04-06 23:09 UTC, Tratcher approved these changes

2017-04-06 23:09 UTC, Tratcher commented on src/Microsoft.AspNetCore.Http.Extensions/RangeParser.cs
> +        public static ICollection<RangeItemHeaderValue> ParseRange(HttpContext context, RequestHeaders requestHeaders, DateTimeOffset lastModified, EntityTagHeaderValue etag)
Some of your MVC file result types won't always have an etag or lastmodified right? What will you do there? or will null work as expected?

2017-04-06 23:17 UTC, Tratcher commented on src/Microsoft.AspNetCore.Http.Extensions/RangeParser.cs
> +                if (ignoreRangeHeader)
new line so this doesn't look like an else-if

2017-04-07 00:34 UTC, jbagga commented
@Tratcher I added `null` checks and made `lastModified` and `etag` optional params. Is that acceptable?

2017-04-07 02:56 UTC, Tratcher approved these changes

2017-04-07 02:56 UTC, Tratcher commented on src/Microsoft.AspNetCore.Http.Extensions/RangeParser.cs
> +        public static ICollection<RangeItemHeaderValue> ParseRange(HttpContext context, RequestHeaders requestHeaders, DateTimeOffset? lastModified = null, EntityTagHeaderValue etag = null)
Default params are not allowed in most of our APIs.

2017-04-07 02:56 UTC, Tratcher commented on src/Microsoft.AspNetCore.Http.Extensions/RangeParser.cs
> +                    if (lastModified != null && lastModified > ifRangeHeader.LastModified)
!lastModified.HasValue

2017-04-07 21:17 UTC, jbagga commented
Closing as this has been addressed in https://github.com/aspnet/StaticFiles/pull/185

2017-04-07 21:17 UTC, closed without merging