[Prototype] Async RequestOptions
aspnet/HttpAbstractions pull request #943
Opened 2017-09-21 23:42 UTC by HaoK

Just playing around with this so far...

Adds an Async configure that is given the HttpContext

            services.ConfigureAsync<TestOptions>((name, o, ctx) => {
                o.Context = ctx;
                return Task.FromResult(0);
            });

Also short cut to access request options directly off HttpContext:

            var options = await context.GetOptionsAsync<TestOptions>(Options.DefaultName);

This would be purely additive, but give us both async and per request options (with direct access to the context)

Any Thoughts?  @davidfowl @ajcvickers @divega

2017-09-22 01:18 UTC, davidfowl commented
Why? I'm no type sure I like this first class way of coupling options to the http request. This is about the flighting scenarios right?

2017-09-22 01:21 UTC, davidfowl requested changes
This looks like a parallel subsystem to options with an additional object (the http request). Why can people Just use the IHttpContextAccessor if they need this

2017-09-22 01:21 UTC, davidfowl commented on src/Microsoft.AspNetCore.Http.Extensions/RequestOptions.cs
> +            => services.AddSingleton<IConfigureRequestOptions<TOptions>>(new ConfigureRequestOptions<TOptions>(configure));
Why isn't this called ConfigureRequestOptins? Why is this even first class?

2017-09-22 01:43 UTC, Tratcher commented
Who asked for this? What were their scenarios? There has been some discussion around this for Authentication, no?

2017-09-22 02:40 UTC, HaoK commented
How to compute options per request is one of the most common questions, but yeah this mostly grew out of the per request authentication PR.  We have also ran into not being able to do async options config in a few places as well, usually related to wanting to configure options by calling into an async method.

So if we had something like this, then we could accomplish switching between default authentication policies per request like this.

```
services.ConfigureRequestOptions<AuthenticationOptions>(options, ctx => options.DefaultPolicy = ComputeDefault(ctx))
```

We'd just need to update the middleware to use request options instead of normal options.  

But yeah this is basically sugar for what would be today: use IOptionsSnapshot + custom IConfigureOptions that takes HttpContextAccessor and uses it to compute options for the request

2018-02-02 00:25 UTC, davidfowl commented
Closing this out @HaoK

2018-02-02 00:25 UTC, closed without merging